### ISSUE TITLE
Layer.frameMinX vs Layer.frame.minX

### ISSUE THREAD

**Issue by saniul** [Khan/Prototope#26]
Feels weird having both of those sets of properties.

How about we just always use the `Layer.frame.minX` lot? We could also make these properties writable.

**Comment by andymatuschak** [comment]
Ditto it feeling weird.

**Comment by jbrennan** [comment]
Andy and I chatted about this briefly the other day, but no reason not to talk publicly about it here, too.

For some historical background, I’ve often added layout helper properties like `.x` and `.y` when dealing with views, but those are shortcuts for `frame.origin.x/y`. When I added the layout helpers to prototope, `Layer` already defined `x` and `y`, but with respect to the `position` of the layer (which for all intents and purposes, is the layer’s centre with respect to its parent layer).

`layer.frameMinX` etc. are definitely awkward. I’d love to get rid of them and instead change the meaning of `layer.x` to be “the x of the layer’s frame’s origin` but I didn’t want to make that change without running it by everyone, especially because it may break things.

I find working with a layer’s centre to be less useful than its origin, at least in the case of positioning. It’s a nice shortcut for positioning under a finger, for example, but even then you really want to offset it by the touch location anyway, so at that point, it’s about as useful as origin.

The other reason for adding a property instead of just accessing it through the frame directly is that felt like a leaky abstraction and I wanted to avoid it (I know the name I chose didn’t do a very good job of that :P).

So, thoughts on getting rid of the min methods and redefining `Layer.x/y` to be relative to the frame origin?

**Comment by andymatuschak** [comment]
Makes sense. @may-li, is that cool with you?

**Comment by jbrennan** [comment]
It’s also possible there are good reasons for leaving `x` and `y` the way they are, but I’m not as familiar with prototyping in this way but I’d love to know the benefits too :)

**Comment by saniul** [comment]
If we change `position` (and `x` and `y`) to mean `origin`, we could expose a `center` property and let users use that whenever they see fit.

**Comment by may-li** [comment]
@andymatuschak yeah this has a lot of confusion potential in my experience. For example, if I were coming to this out of nowhere, I'd be unsure whether origin is upper left or lower left – perhaps this is something I should take for granted but I don't, probably because I've worked with both in the past, or perhaps because mathematical coordinate systems point the opposite way from most software building coordinate systems. So in the case that we change the meaning of position to be the origin (upper left?) does that mean they should assume scaling and rotation happen around the origin? Or would we somehow decouple the position from the anchorPoint then?

**Comment by andymatuschak** [comment]
I think my proposal is that "position" means whatever the anchor point is, "x" means the upper left x point, and we don't change the meaning of the anchor point (ie rotation and scaling work as they do now)

**Comment by jbrennan** [comment]
How about `originX` and `originY`, referring to the origin of the layer’s frame (i.e., top left corner), and leaving `position` and `x` and `y` alone, so as to keep them consistent (and centred).

**Comment by may-li** [comment]
That sounds reasonable to me! I think that sounds great for the way we plan to use it. I also like that it's clear about what it means — I was worried that having x, y differ from position.x and position.y could be confusing...

**Comment by jbrennan** [comment]
Done!
