### ISSUE TITLE
Protoscope sometimes can’t find images

### ISSUE THREAD

**Issue by jbrennan** [Khan/Prototope#28]
I’m not sure why this is, but it ends up giving us a fatalError in the Image type because it can’t always load the image (even though it’s present).

**Comment by andymatuschak** [comment]
Yikes. Can you post an example that exhibits the issue?

**Comment by jbrennan** [comment]
Hmmm. OK I think I figured it out. The problem is when you broadcast just a `js` file, not the directory *containing* the `js` file.

**Comment by andymatuschak** [comment]
Oh, that makes sense. I basically didn't intend that to work, but now that you point it out, maybe it should.

My thinking was that if you drop a .js on Protocaster, it just broadcasts that file. Maybe it should broadcast everything in the folder? Is that weird?

At minimum, we should propagate these kinds of errors through `Environment.exceptionHandler` so that e.g. Protoscope can display the error as a protonope and send it back to the host.

**Comment by saniul** [comment]
> Maybe it should broadcast everything in the folder? Is that weird?

I think it’s totally reasonable to load the whole thing when only main.js was selected. In fact, it’s what I expected it to do the first time I tried it and encountered the same problem @jbrennan did.

**Comment by andymatuschak** [comment]
OK!
